spring:
  application:
    name: sov-cyberhub
  datasource:
    url: jdbc:sqlite:cyber_hub_logs.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate.ddl-auto: update
    show-sql: false

logging:
  pattern:
    level: "%5p [correlationId=%X{correlationId:-}]"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    filter: true

management:
  endpoints:
    health:
      show-details: always
    web:
      base-path: /actuator
      exposure:
        include: "*"

cyberwrite:
  insurers:
    client:
      baseUrl: https://api-test.cyberwrite.com/v2.0.8
      key: 353HQ3RIfy1av5fVbgknq5CWuAcrGhGb9mbWIhip
      insurer: fc97e035-11f7-4401-93b4-a3b142d286ff

cybercube:
  odap:
    client:
      baseUrl: https://api.pm.cybcube.com
      key: 6WUpjmGY0ktKy4KnCoZddmhfd7Vu7lI/yhSigQ6gylr8mfVSPGl47SofoBfOOePd/7pH2cq0wRW99EIU7sT3HA==

